/** Privacy notice shown in the app (Settings → Privacy). Keep in step with website/privacy. */
export const PRIVACY_CONTACT_EMAIL = 'eshaantr.mukku@gmail.com';

export const PRIVACY_POLICY_URL = 'https://eshaantrmukku-del.github.io/byt-website/privacy/';

export const ACCOUNT_DELETION_URL = 'https://eshaantrmukku-del.github.io/byt-website/delete-account/';

export const ACCOUNT_DELETION_MAILTO =
  `mailto:${PRIVACY_CONTACT_EMAIL}?subject=${encodeURIComponent('Delete my BYT account and data')}&body=${encodeURIComponent(
    'Please delete my BYT account and all associated data.\n\nAccount email: '
  )}`;

export const PRIVACY_LAST_UPDATED = '4 October 2026';

export type PrivacySection = {
  id: string;
  title: string;
  paragraphs: string[];
  bullets?: string[];
};

export const PRIVACY_SECTIONS: PrivacySection[] = [
  {
    id: 'overview',
    title: 'The short version',
    paragraphs: [
      'BYT (Build Your Tomorrow) is a private coaching app. What you share stays tied to your account and is used only to run BYT for you.',
      'We don’t sell your data, and we don’t use it for advertising.',
    ],
  },
  {
    id: 'collect',
    title: 'What we store',
    paragraphs: ['Only what you give BYT while using it:'],
    bullets: [
      'Account: your name and email address',
      'Profile: date of birth, what you do, your goals and the context you choose to add (income, lifestyle, struggles, notes for your coach)',
      'Goals, daily check-ins (mood, energy, stress, sleep) and journal entries',
      'Conversations with your coach, and voice audio while you use voice coaching',
    ],
  },
  {
    id: 'not-collected',
    title: 'What we don’t collect',
    paragraphs: [
      'BYT does not ask for or store a profile photo. We don’t access your contacts, location or photos.',
    ],
  },
  {
    id: 'use',
    title: 'How it’s used',
    paragraphs: [
      'To keep you signed in, sync your data across your devices, and give your coach the context it needs to be useful. Your coach uses your profile as quiet background — it isn’t shown to anyone else.',
    ],
  },
  {
    id: 'providers',
    title: 'Who helps us run BYT',
    paragraphs: [
      'Your account and data are stored with Google Firebase. Coaching replies are generated by an AI model, and voice features use a speech provider. These services process data only to provide those features.',
    ],
  },
  {
    id: 'security',
    title: 'Keeping it private',
    paragraphs: [
      'Your data is only accessible to your signed-in account. Security rules on our servers enforce this — not just the app.',
    ],
  },
  {
    id: 'rights',
    title: 'Your choices',
    paragraphs: [
      'You can edit your profile at any time and delete goals or journal entries in the app.',
      `To delete your account and all of its data, email ${PRIVACY_CONTACT_EMAIL} from your account email with the subject “Delete my BYT account and data”. We’ll confirm once it’s done.`,
    ],
  },
  {
    id: 'contact',
    title: 'Contact',
    paragraphs: [`Questions about privacy: ${PRIVACY_CONTACT_EMAIL}`],
  },
];
